---
title: "Campaign Narrative Reflection"
author: "Kaitlyn Vu"
date: '2024-11-22'
slug: campaign-narrative-reflection
categories: []
tags: []
---

## Introduction

For my campaign reflection, I decided to focus on **Nevada**. President-elect Donald Trump [won](https://apnews.com/projects/election-results-2024/nevada/?r=0) Nevada in the 2024 Presidential Election with 51.58% of the state's two-party popular vote to Vice President Kamala Harris' 48.42%. Trump's victory in Nevada was declared early on Saturday November 9, beating Harris by approximately 46,000 votes.

## Nevada: A Brief Overview

Since 1980, the Silver State's dramatic population growth — including 35% growth between 2000 and 2010 — [has increased](https://www.270towin.com/states/Nevada) its number of electoral votes from three to six. The influx of voters has solidly established Nevada as a swing state: however, Democratic presidential candidates have prevailed in the state over the past twenty years. Former President Obama captured Nevada in both of his presidential campaigns and Secretary Clinton [defeated](https://www.nvsos.gov/silverstate2016gen/) Trump with 51.29% of the state's two-party popular vote in 2016. Four years ago, President Biden [won](https://www.nvsos.gov/silverstate2020gen/USPresidential/) the state with 51.22% of the popular vote share to Trump's 48.78%. In Nevada, Democrats have often [turned](https://www.nytimes.com/2023/01/24/us/politics/reid-machine.html) to the "Reid Machine" — the voter coalition of the late former majority leader Sen. Harry Reid.

Nevada's population [reached](https://tax.nv.gov/wp-content/uploads/2024/10/Nevada-County-Population-Projections-2024-to-2043.pdf) 3.24 million in 2023 with projected growth to 3.94 million by 2043. Clark County (Las Vegas) and Washoe County (Reno) — both which tend to vote blue — dominate most of the population growth, while rural counties such as Nye, Douglas, and Esmeralda show slower or more moderate population increases. The average household income is \$97,955, which is 7% lower than the national average; unemployment in the state increased from 5.1% to 5.5% in 2024.

In terms of demographics, 1 in 5 voters in Nevada [are](https://www.npr.org/2024/09/06/nx-s1-5101765/swing-states-demographics-electorate) Latino — that subgroup is up 7 points since 2008. White non-college voters are down 14 points since 2008, while AAPI voters are now almost 10% of the eligible voter population in Nevada. In 2024, registered nonpartisans outnumbered voters of either party, comprising more than 30% of the electorate when combined with third party registrants.

For the Senate, incumbent Democratic Sen. Jacky Rosen [defeated](https://apnews.com/projects/election-results-2024/nevada/?r=29866) Republican challenger Sam Brown in a close race to hold onto her Senate seat. Rosen gained 50.87% of the two-party popular vote to 49.13% for Brown — the candidates were separated by about 24,000 votes.

For the House, all four incumbent representatives successfully [defended](https://ballotpedia.org/United_States_House_of_Representatives_elections_in_Nevada,_2024) their seats: Rep. Dina Titus (D-NV 1st District), Rep. Mark Amodei (R-NV 2nd District), Rep. Susie Lee (D-NV 3rd District), and Rep. Steven Horsford (D-NV 4th District) all won re-election in relatively tight races.

There were 7 ballot questions for this year's election as well. Nevadian voters [passed](https://ballotpedia.org/Nevada_2024_ballot_measures) all questions except for Question 1 (Nevada Board of Regents) and Question 3 (open primaries and ranked-choice voting). Question 2, 4, 5, 6, and 7 concerned language on disabilities in the state constitution, language on slavery in the state constitution, diaper tax exemptions, abortion, and voter IDs, respectively. Notably, Question 6 codified the right to an abortion up to 24 weeks in the state constitution.

## Predicted vs Actual Results

### How close was my prediction?

My state model predicted that Harris would win Nevada with 52.32% of the state's two-party popular vote to Trump's 47.68%. At the prediction's lower bound, Trump would win the state with 53% to Harris' 47%. At the prediction's higher bound, Harris would win the state with 57.65% to Trump's 42.35%.

In reality, Trump carried the state with 51.58% of the popular vote share. That means that my prediction was off by 3.9 percentage points, which was enough to carry Trump to victory.

### How close were the experts?

Originally categorized as "Toss Up," [Sabato's Crystal Ball](https://centerforpolitics.org/crystalball/2024-president/) deemed Nevada "Leans D" in their final Electoral College ratings. Both [Cook Political Report](https://www.cookpolitical.com/ratings/presidential-race-ratings) and [FiveThirtyEight](https://www.270towin.com/maps/consensus-2024-presidential-election-forecast) categorized Nevada as "Toss Up" in their respective forecasts.

I believe that the experts were largely correct to designate the Silver State as a "Toss Up" in their forecasts, even though Trump won by a slightly larger margin than Biden did four years ago. More specifically, Biden won Nevada by 33,596 votes in 2020, while Trump won by about 46,000 votes this year. All factors considered, that is still a closely contested two-party race.

## Evaluation of the Campaigns

In terms of the volume of campaign stops, it appears that the campaigns were about even. Harris first [hit](https://nevadacurrent.com/2024/08/11/harris-walz-energize-crowd-at-first-nevada-rally-as-democratic-presidential-ticket/) the campaign trail in Nevada roughly three weeks after Biden withdrew from the race: Las Vegas was the final stop in a five-day tour across the swing states. The rally drew in more than 12,000 people, one of the largest Nevada rallies in modern political history. Harris also [visited](https://thenevadaindependent.com/article/four-takeaways-from-kamala-harris-speech-in-las-vegas) Las Vegas again in late September and Reno in late October, [accompanied](https://thenevadaindependent.com/article/takeaways-from-kamala-harris-closing-pitch-in-nevada) by celebrity guests such as Mexican rock band Maná and actress Jennifer Lopez. Gov. Walz also [held](https://www.kolotv.com/2024/10/09/walz-returns-northern-nevada-campaign-promised/) a rally in Reno in early October, returning to Northern Nevada after the Davis Fire forced the campaign to cancel an earlier stop. After the RNC, Trump [visited](https://knpr.org/show/knprs-state-of-nevada/2024-09-27/harris-trump-campaigns-make-more-stops-in-nevada-with-3-weeks-to-early-voting) Las Vegas in late September and twice towards the of October. He also [rallied](https://thenevadaindependent.com/article/four-takeaways-from-trumps-rally-in-reno) in Reno in mid-October. Similarly, Vice President-elect Vance [led](https://nevadacurrent.com/2024/10/23/vance-pushes-early-voting-claims-immigrants-to-blame-for-housing-crisis-during-vegas-campaign-stop/) a rally in Las Vegas in late October.

Regarding campaign spending, the Harris campaign [out-spent](https://www.opensecrets.org/states/NV/presidential/2024) Trump statewide by about \$400,000 — both campaigns spent over 6 million in the Silver State. Looking at the top metro areas, Trump poured more funds into Las Vegas while Harris almost doubled Trump's spending in Reno. Fun to note: Harris [ran](https://www.fastcompany.com/91219185/harris-campaigns-sphere-ad) the first-ever political ad on the Sphere in Las Vegas, which happens to be the largest screen in the world.

In terms of polling and candidate favorability, Harris and Trump [were in](https://projects.fivethirtyeight.com/polls/nevada/) a dead heat heading into the fall. Harris enjoyed a brief bump of support in the statewide polls after the DNC, although aggregate polling for the candidates eventually converged closer to Election Day. Especially towards he end of the cycle, both candidates [honed in](https://www.npr.org/2024/10/31/nx-s1-5172910/2024-election-kamala-harris-donald-trump-arizona-nevada) on the issues important to Nevada's relatively large contingent of Latino voters, including immigration and the economy.

## Assessing Deviations from Forecasted Outcomes

I think 2 campaign- or candidate-related factors may have contributed to deviations from forecasted election outcomes.

The first is party affiliation. As noted in the write-up for my final prediction, Kim and Zilinsky (2024) [found](https://link.springer.com/article/10.1007/s11109-022-09816-z) that partisan affiliation is a strong predictor of the national two-party vote share. However, since August 2023, nonpartisans [have comprised](https://thenevadaindependent.com/article/analysis-harris-banked-on-wide-nonpartisan-support-in-nevada-it-apparently-never-came) the largest share of registered voters in the Silver State. In Clark and Washoe counties — home to nearly 90% of the state’s registered voters — preliminary data indicates that 330,000 nonpartisans voted in the election, accounting for over a quarter of county turnout. The Harris campaign had hoped to secure substantial support from this group: even as early turnout data showed significant leads among registered Republicans, Democrats remained optimistic about their prospects with nonpartisans. However, nonpartisans didn't shift toward Democrats as strongly as anticipated, failing to offset the marked increase in Republican registered voters since 2020. Harris thus under-performed compared to Biden in the two major counties where she needed stronger results: she won Clark County with a margin of 2.68% and Washoe County with a margin of 1.02%, falling significantly short to Biden's 2020 margins of 9.54% and 4.64%, respectively. As such, the Harris campaign's inability to effectively leverage the growing nonpartisan voter bloc in Nevada likely contributed to deviations from forecasted outcomes, especially those that included partisan affiliation as a predictor.

The second was the economy, arguably the defining story of this election. Time and time again, research highlights the importance of economic fundamentals in presidential elections, as [emphasized](https://press.princeton.edu/books/hardcover/9780691169446/democracy-for-realists?srsltid=AfmBOorl6iN4qgweThT5hVNygA3GYiEx8IZYUksJEgexdWLE3Es2imza) by Achen and Bartels in *Democracy for Realists* (2016). As of November, Nevada is [tied](https://www.bls.gov/web/laus/laumstrk.htm) for the highest unemployment rate among states; the Silver State has also been hit particularly hard by inflation. Local political reporter Megan Messerly aptly [described](https://www.politico.com/newsletters/politico-nightly/2024/10/15/what-the-campaign-feels-like-in-nevada-00183798) the electoral effects of economic headwinds: “When the rest of the country catches a cold, Nevada catches the flu." The Trump campaign [capitalized](https://thenevadaindependent.com/article/anatomy-of-a-red-wave-how-trump-won-nevada) on voter discontent, effectively hammering home economic frustrations alongside concerns over immigration and public safety. Republican operatives likewise credited the campaign's robust voter-targeting efforts and Trump's promise to end taxation on tips for resonating among voters disillusioned with Biden's economy. I think Peter Koltak — a Democratic strategist of Sen. Sanders' Nevada campaign — put it best: “...I do think we had a bloc of voters who were still surly about the economy, still surly about inflation and prices. Democrats, by being the incumbent party, we're always going to pay some penalty for that." Despite widespread understanding of the importance of the economy, the Democratic campaign appeared to be reactive in addressing such concerns. Harris faced the enviable task of defending the Biden administration's economic record, while Trump's campaign gained the advantage with a more targeted and concrete economic message.

## Conclusion

Despite trailing in campaign spending, the Trump campaign effectively addressed the economic concerns of Nevada's electorate — securing the first Republican presidential victory in the Silver State in two decades. This electoral outcome pushes Democrats to seriously reassess their campaign strategy in Nevada, especially as the state's voter demographics continue to shift in the coming years. The Reid Machine likely played a crucial role in preventing further Democratic losses down-ballot, but Democrats need to chart a new path forward if they are to flip Nevada in 2028.

As I complete my final assignment for GOV 1347, I wanted to once again thank the incredible teaching team. Also, a very special shout-out to my classmate and good friend Victor Bowker for his moral support and enthusiasm throughout this semester. I'm excited to carry forward the lessons I've gained from this class as I continue my studies in the Government Department at Harvard College!
